/* ═══════════════════════════════════════════════════════════
   AGROCONNECT - DATA.JS
   All mock data for the prototype
   ═══════════════════════════════════════════════════════════ */

const AC_DATA = {

  /* ── INPUT TYPES ── */
  inputTypes: [
    { id: 'all',          label: 'All Inputs',             emoji: '🛒', color: '#1E8B4C', bg: '#F0FDF4' },
    { id: 'seeds',        label: 'Seeds & Planting',       emoji: '🌱', color: '#16A34A', bg: '#DCFCE7' },
    { id: 'fertilizers',  label: 'Fertilizers',            emoji: '🧪', color: '#2563EB', bg: '#DBEAFE' },
    { id: 'crop-protect', label: 'Crop Protection',        emoji: '🌿', color: '#7C3AED', bg: '#EDE9FE' },
    { id: 'equipment',    label: 'Equipment & Tools',      emoji: '🚜', color: '#D97706', bg: '#FEF3C7' },
    { id: 'post-harvest', label: 'Post-Harvest & Storage', emoji: '📦', color: '#0EA5E9', bg: '#E0F2FE' },
  ],

  subCategories: {
    'seeds':        ['All Seeds', 'Cereals', 'Vegetables', 'Tubers', 'Legumes', 'Cash Crops'],
    'fertilizers':  ['All Fertilizers', 'NPK Blends', 'Urea', 'DAP', 'SSP', 'Organic & Compost', 'Foliar Feed'],
    'crop-protect': ['All Crop Protection', 'Herbicides', 'Insecticides', 'Fungicides', 'Bio-Pesticides'],
    'equipment':    ['All Equipment', 'Hand Tools', 'Irrigation Kits', 'Sprayers', 'Threshers & Mills'],
    'post-harvest': ['All Post-Harvest', 'Grain Bags', 'Silos & Drums', 'Fumigants', 'Weighing Scales'],
  },

  /* ── PRODUCTS (seeds + all inputs) ── */
  products: [
    // ── CEREALS ──
    {
      id: 'PRD-001',
      name: 'Hybrid Maize Seeds',
      fullName: 'Hybrid Maize Seeds (Premium Quality)',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'All Regions',
      price: 15000,
      unit: 'kg',
      stock: 450,
      rating: 4.5,
      reviews: 128,
      supplier: 'SEEDCO Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00234',
      germination: '95%',
      purity: '99%',
      bgColor: 'green',
      description: 'Premium hybrid maize seeds specially selected for Nigerian climate. High yield potential with excellent disease resistance. Perfect for both commercial and subsistence farming.',
      features: ['High germination rate (>95%)', 'Matures in 90-100 days', 'Expected yield: 4-6 tons/hectare', 'Disease resistant'],
      inStock: true
    },
    {
      id: 'PRD-002',
      name: 'Rice Seeds (FARO 44)',
      fullName: 'Rice Seeds FARO 44 - Certified',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'South West',
      price: 25000,
      unit: 'kg',
      stock: 280,
      rating: 4.8,
      reviews: 94,
      supplier: 'Notore Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00118',
      germination: '92%',
      purity: '98%',
      bgColor: 'yellow',
      description: 'FARO 44 is a high-yielding, early-maturing rice variety adapted to lowland ecology. Recommended by FMARD for Nigerian farmers.',
      features: ['Early maturing (105-115 days)', 'Flood tolerant', 'Yield: 5-7 tons/hectare', 'FMARD recommended'],
      inStock: true
    },
    {
      id: 'PRD-003',
      name: 'Rice Seeds (FARO 52)',
      fullName: 'Rice Seeds FARO 52 - Upland Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North Central',
      price: 22000,
      unit: 'kg',
      stock: 190,
      rating: 4.6,
      reviews: 71,
      supplier: 'Notore Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00119',
      germination: '90%',
      purity: '97%',
      bgColor: 'yellow',
      description: 'FARO 52 is an upland rice variety suited to well-drained soils across the Nigerian Middle Belt. Performs excellently in rain-fed conditions.',
      features: ['Upland adapted', 'Rain-fed suitable', 'Maturity: 110-120 days', 'Blast resistant'],
      inStock: true
    },
    {
      id: 'PRD-004',
      name: 'Open Pollinated Maize',
      fullName: 'Open Pollinated Maize - SUWAN-1-SR',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North West',
      price: 11000,
      unit: 'kg',
      stock: 600,
      rating: 4.2,
      reviews: 88,
      supplier: 'IITA Seedsystem',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00301',
      germination: '88%',
      purity: '96%',
      bgColor: 'green',
      description: 'SUWAN-1-SR is a Striga-resistant open pollinated maize variety developed specifically for savanna conditions in northern Nigeria.',
      features: ['Striga resistant', 'Drought tolerant', 'Yield: 3-5 tons/hectare', 'Suitable for Guinea Savanna'],
      inStock: true
    },
    {
      id: 'PRD-005',
      name: 'Sorghum Seeds (SK 5912)',
      fullName: 'Sorghum Seeds - SK 5912 Hybrid',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North West',
      price: 18000,
      unit: 'kg',
      stock: 0,
      rating: 4.1,
      reviews: 33,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00201',
      germination: '91%',
      purity: '98%',
      bgColor: 'green',
      description: 'Drought-tolerant sorghum variety suitable for the Nigerian savanna belt. Excellent for both food and animal feed.',
      features: ['Drought tolerant', 'Stem borer resistant', 'Maturity: 95-105 days', 'Dual purpose'],
      inStock: false
    },
    {
      id: 'PRD-006',
      name: 'Sorghum Seeds (SAMSORG 17)',
      fullName: 'Sorghum Seeds - SAMSORG 17',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North East',
      price: 14500,
      unit: 'kg',
      stock: 340,
      rating: 4.4,
      reviews: 56,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00202',
      germination: '89%',
      purity: '97%',
      bgColor: 'green',
      description: 'SAMSORG 17 is an improved sorghum variety with good grain quality and high yield under semi-arid conditions in northeast Nigeria.',
      features: ['Semi-arid adapted', 'Good grain quality', 'Maturity: 90-100 days', 'High yield potential'],
      inStock: true
    },
    {
      id: 'PRD-007',
      name: 'Millet Seeds (SOSAT-C88)',
      fullName: 'Pearl Millet - SOSAT-C88 Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North West',
      price: 9500,
      unit: 'kg',
      stock: 410,
      rating: 4.3,
      reviews: 41,
      supplier: 'Kano Agro Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00312',
      germination: '87%',
      purity: '95%',
      bgColor: 'yellow',
      description: 'SOSAT-C88 pearl millet variety ideal for the Sahel and Sudan savanna zones. Excellent downy mildew resistance and early maturity.',
      features: ['Downy mildew resistant', 'Early maturing (75-80 days)', 'Drought tolerant', 'High grain yield'],
      inStock: true
    },
    {
      id: 'PRD-008',
      name: 'Wheat Seeds (SIETE CERROS)',
      fullName: 'Wheat Seeds - Siete Cerros Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cereals',
      region: 'North West',
      price: 28000,
      unit: 'kg',
      stock: 120,
      rating: 4.0,
      reviews: 28,
      supplier: 'Kano Agro Seeds',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '86%',
      purity: '95%',
      bgColor: 'yellow',
      description: 'Wheat variety adapted to irrigation farming in northern Nigeria. Best planted in the dry season with adequate irrigation.',
      features: ['Irrigation adapted', 'Dry season planting', 'Maturity: 100-120 days', 'Good milling quality'],
      inStock: true
    },

    // ── LEGUMES ──
    {
      id: 'PRD-009',
      name: 'Cowpea Seeds (IT99K-573)',
      fullName: 'Cowpea Seeds - IT99K-573-1-1',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'North Central',
      price: 13000,
      unit: 'kg',
      stock: 520,
      rating: 4.7,
      reviews: 103,
      supplier: 'IITA Seedsystem',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00145',
      germination: '93%',
      purity: '98%',
      bgColor: 'green',
      description: 'IT99K-573-1-1 is a dual-purpose cowpea variety providing both grain and fodder. Resistant to major cowpea pests and diseases.',
      features: ['Dual purpose (grain + fodder)', 'Bruchid resistant', 'Maturity: 60-65 days', 'High protein content'],
      inStock: true
    },
    {
      id: 'PRD-010',
      name: 'Cowpea Seeds (SAMPEA 20T)',
      fullName: 'Cowpea Seeds - SAMPEA 20T Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'All Regions',
      price: 11500,
      unit: 'kg',
      stock: 380,
      rating: 4.5,
      reviews: 79,
      supplier: 'IITA Seedsystem',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00146',
      germination: '91%',
      purity: '97%',
      bgColor: 'green',
      description: 'SAMPEA 20T is a Striga-tolerant cowpea variety with good resistance to thrips and aphids. Suitable for both northern and southern Nigeria.',
      features: ['Striga tolerant', 'Aphid resistant', 'Early maturing (58-62 days)', 'Wide adaptation'],
      inStock: true
    },
    {
      id: 'PRD-011',
      name: 'Soybean Seeds (TGX 1951-3F)',
      fullName: 'Soybean Seeds - TGX 1951-3F',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'North Central',
      price: 16000,
      unit: 'kg',
      stock: 290,
      rating: 4.6,
      reviews: 65,
      supplier: 'Sahel Agri Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00178',
      germination: '90%',
      purity: '98%',
      bgColor: 'green',
      description: 'TGX 1951-3F is a high-yielding soybean variety suited to the Guinea and Sudan savanna zones. Popular for both food and industrial use.',
      features: ['High oil content (21%)', 'Matures in 95-100 days', 'Yield: 2-3 tons/hectare', 'Broad adaptation'],
      inStock: true
    },
    {
      id: 'PRD-012',
      name: 'Groundnut Seeds (SAMNUT 24)',
      fullName: 'Groundnut Seeds - SAMNUT 24',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'North West',
      price: 19000,
      unit: 'kg',
      stock: 175,
      rating: 4.4,
      reviews: 58,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00189',
      germination: '88%',
      purity: '96%',
      bgColor: 'orange',
      description: 'SAMNUT 24 is a rosette-resistant groundnut variety with good shelling percentage and oil content. Well adapted to northern Nigeria.',
      features: ['Rosette resistant', 'High shelling percentage', 'Oil content: 48%', 'Matures in 90-95 days'],
      inStock: true
    },
    {
      id: 'PRD-013',
      name: 'Groundnut Seeds (SAMNUT 26)',
      fullName: 'Groundnut Seeds - SAMNUT 26',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'North East',
      price: 21000,
      unit: 'kg',
      stock: 140,
      rating: 4.3,
      reviews: 44,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00190',
      germination: '87%',
      purity: '95%',
      bgColor: 'orange',
      description: 'SAMNUT 26 is an improved groundnut variety with late leafspot tolerance and high yield potential under semi-arid conditions.',
      features: ['Late leafspot tolerant', 'High yield (2-2.5 t/ha)', 'Drought tolerant', 'Good market quality'],
      inStock: true
    },
    {
      id: 'PRD-014',
      name: 'Bambara Groundnut',
      fullName: 'Bambara Groundnut - TVSu 672',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Legumes',
      region: 'North Central',
      price: 8500,
      unit: 'kg',
      stock: 220,
      rating: 4.1,
      reviews: 31,
      supplier: 'Sahel Agri Seeds',
      supplierVerified: false,
      verification: 'none',
      verificationNumber: null,
      germination: '82%',
      purity: '93%',
      bgColor: 'orange',
      description: 'Bambara groundnut is a drought-hardy legume crop popular in northern and central Nigeria. High protein and energy content.',
      features: ['Drought hardy', 'Low input requirement', 'Matures in 120-150 days', 'High nutrition value'],
      inStock: true
    },

    // ── VEGETABLES ──
    {
      id: 'PRD-015',
      name: 'Tomato Seeds (Roma VF)',
      fullName: 'Tomato Seeds - Roma VF Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'North Central',
      price: 8000,
      unit: 'kg',
      stock: 850,
      rating: 4.3,
      reviews: 67,
      supplier: 'AgriPro Seeds',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '88%',
      purity: '96%',
      bgColor: 'pink',
      description: 'Roma VF tomato seeds ideal for Nigerian growing conditions. Heat-tolerant and suitable for both wet and dry season cultivation.',
      features: ['Heat tolerant', 'Fusarium wilt resistant', 'Maturity: 75-80 days', 'High fruit set'],
      inStock: true
    },
    {
      id: 'PRD-016',
      name: 'Tomato Seeds (INSTANCE F1)',
      fullName: 'Tomato Seeds - Instance F1 Hybrid',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'All Regions',
      price: 32000,
      unit: 'kg',
      stock: 95,
      rating: 4.9,
      reviews: 112,
      supplier: 'Syngenta Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00267',
      germination: '96%',
      purity: '99%',
      bgColor: 'pink',
      description: 'Instance F1 is a premium hybrid tomato with very high yield potential and excellent shelf life. Preferred by commercial farmers.',
      features: ['F1 Hybrid', 'Very high yield (60-80 t/ha)', 'Long shelf life', 'Uniform fruit size'],
      inStock: true
    },
    {
      id: 'PRD-017',
      name: 'Pepper Seeds (Tatase)',
      fullName: 'Tatashe (Bell Pepper) Seeds',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'South West',
      price: 7500,
      unit: 'kg',
      stock: 430,
      rating: 4.2,
      reviews: 49,
      supplier: 'AgriPro Seeds',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '85%',
      purity: '94%',
      bgColor: 'orange',
      description: 'Local tatashe (bell pepper) variety well adapted to Nigerian conditions. Widely used in cooking and has strong local market demand.',
      features: ['Strong local demand', 'Suitable for wet & dry seasons', 'Maturity: 70-80 days', 'High flesh content'],
      inStock: true
    },
    {
      id: 'PRD-018',
      name: 'Scotch Bonnet Seeds',
      fullName: 'Scotch Bonnet Pepper (Rodo) Seeds',
      emoji: '🌱️',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'South West',
      price: 9000,
      unit: 'kg',
      stock: 310,
      rating: 4.5,
      reviews: 88,
      supplier: 'GreenFarm Seeds',
      supplierVerified: false,
      verification: 'none',
      verificationNumber: null,
      germination: '83%',
      purity: '93%',
      bgColor: 'pink',
      description: 'Scotch bonnet (rodo) is one of the most commercially important pepper varieties in Nigeria. Very high demand in both fresh and dried markets.',
      features: ['Very high market value', 'Matures in 80-90 days', 'Strong aroma', 'High capsaicin content'],
      inStock: true
    },
    {
      id: 'PRD-019',
      name: 'Okra Seeds (NHAe 47-4)',
      fullName: 'Okra Seeds - NHAe 47-4 Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'South East',
      price: 5500,
      unit: 'kg',
      stock: 670,
      rating: 4.4,
      reviews: 76,
      supplier: 'AgriPro Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00334',
      germination: '87%',
      purity: '95%',
      bgColor: 'green',
      description: 'NHAe 47-4 is an improved okra variety with yellow vein mosaic virus resistance. High pod yield and good pod quality.',
      features: ['Mosaic virus resistant', 'High pod yield', 'Maturity: 50-55 days', 'Multiple harvests'],
      inStock: true
    },
    {
      id: 'PRD-020',
      name: 'Spinach Seeds (Amaranthus)',
      fullName: 'African Spinach - Amaranthus Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'South West',
      price: 6500,
      unit: 'kg',
      stock: 320,
      rating: 4.6,
      reviews: 52,
      supplier: 'GreenFarm Seeds',
      supplierVerified: false,
      verification: 'none',
      verificationNumber: null,
      germination: '85%',
      purity: '94%',
      bgColor: 'green',
      description: 'Fast-growing African spinach (Amaranthus) seeds. Highly nutritious and suitable for year-round cultivation with multiple harvests.',
      features: ['Fast growing (21-30 days)', 'High nutrition', 'Multiple harvests possible', 'Heat tolerant'],
      inStock: true
    },
    {
      id: 'PRD-021',
      name: 'Waterleaf Seeds',
      fullName: 'Waterleaf (Talinum) Seeds',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'South South',
      price: 4500,
      unit: 'kg',
      stock: 490,
      rating: 4.3,
      reviews: 38,
      supplier: 'Delta Agro Seeds',
      supplierVerified: false,
      verification: 'none',
      verificationNumber: null,
      germination: '80%',
      purity: '91%',
      bgColor: 'green',
      description: 'Waterleaf (Talinum triangulare) is a popular leafy vegetable in southern Nigeria. Fast growing and thrives in humid conditions.',
      features: ['Grows in humid conditions', 'Ready in 3-4 weeks', 'High demand in south', 'Easy to grow'],
      inStock: true
    },
    {
      id: 'PRD-022',
      name: 'Onion Seeds (BORNO RED)',
      fullName: 'Onion Seeds - Borno Red Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'North East',
      price: 24000,
      unit: 'kg',
      stock: 85,
      rating: 4.7,
      reviews: 92,
      supplier: 'Kano Agro Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00289',
      germination: '89%',
      purity: '97%',
      bgColor: 'pink',
      description: 'Borno Red is Nigeria\'s most popular onion variety. Grown extensively in Sokoto, Kebbi, Kano and Borno states. Excellent storage quality.',
      features: ['Excellent storage life', 'Strong flavour', 'Maturity: 120-150 days', 'High market value'],
      inStock: true
    },
    {
      id: 'PRD-023',
      name: 'Carrot Seeds (DANVERS)',
      fullName: 'Carrot Seeds - Danvers Half Long',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Vegetables',
      region: 'North Central',
      price: 18000,
      unit: 'kg',
      stock: 130,
      rating: 4.2,
      reviews: 41,
      supplier: 'AgriPro Seeds',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '82%',
      purity: '93%',
      bgColor: 'orange',
      description: 'Danvers Half Long carrot variety suited to the Jos Plateau and other highland areas of Nigeria. Good root size and orange colour.',
      features: ['Suited to highlands', 'Good root size', 'Maturity: 70-80 days', 'High vitamin A content'],
      inStock: true
    },

    // ── TUBERS ──
    {
      id: 'PRD-024',
      name: 'Cassava Stems (TME 419)',
      fullName: 'Cassava Stems - TME 419 Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Tubers',
      region: 'South South',
      price: 12000,
      unit: 'bundle',
      stock: 125,
      rating: 4.3,
      reviews: 45,
      supplier: 'IITA Seedsystem',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00089',
      germination: '90%',
      purity: '97%',
      bgColor: 'orange',
      description: 'TME 419 is a mosaic-disease resistant cassava variety with high dry matter content. IITA-certified planting material.',
      features: ['Mosaic resistant', 'High dry matter (38%)', 'Harvest: 9-12 months', 'IITA certified'],
      inStock: true
    },
    {
      id: 'PRD-025',
      name: 'Cassava Stems (UMUCASS 38)',
      fullName: 'Cassava Stems - UMUCASS 38',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Tubers',
      region: 'South East',
      price: 14000,
      unit: 'bundle',
      stock: 200,
      rating: 4.5,
      reviews: 63,
      supplier: 'NRCRI Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00091',
      germination: '92%',
      purity: '98%',
      bgColor: 'orange',
      description: 'UMUCASS 38 is a high-starch cassava variety recommended for industrial processing. Developed by NRCRI Umudike.',
      features: ['High starch content', 'Industrial grade', 'Harvest: 10-12 months', 'NRCRI certified'],
      inStock: true
    },
    {
      id: 'PRD-026',
      name: 'Yam Setts (PONA)',
      fullName: 'Yam Setts - Pona Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Tubers',
      region: 'North Central',
      price: 35000,
      unit: 'bundle',
      stock: 80,
      rating: 4.6,
      reviews: 55,
      supplier: 'Benue Farm Seeds',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '88%',
      purity: '95%',
      bgColor: 'orange',
      description: 'Pona is one of the most prized yam varieties in Nigeria. Premium market value and excellent taste. Popular in Benue, Plateau and Nasarawa states.',
      features: ['Premium market value', 'Excellent taste', 'Harvest: 7-9 months', 'Good storability'],
      inStock: true
    },
    {
      id: 'PRD-027',
      name: 'Yam Setts (AMOPE)',
      fullName: 'Yam Setts - Amope Water Yam',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Tubers',
      region: 'South West',
      price: 28000,
      unit: 'bundle',
      stock: 110,
      rating: 4.4,
      reviews: 47,
      supplier: 'Oyo Agro Seeds',
      supplierVerified: false,
      verification: 'none',
      verificationNumber: null,
      germination: '85%',
      purity: '93%',
      bgColor: 'orange',
      description: 'Amope water yam (Dioscorea alata) with high yield and good cooking quality. Very popular in southwestern Nigeria markets.',
      features: ['High yield variety', 'Good cooking quality', 'Harvest: 7-8 months', 'High market demand in SW'],
      inStock: true
    },
    {
      id: 'PRD-028',
      name: 'Sweet Potato Vines (UMUSPO 3)',
      fullName: 'Sweet Potato Vines - UMUSPO 3',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Tubers',
      region: 'South East',
      price: 7000,
      unit: 'bundle',
      stock: 350,
      rating: 4.3,
      reviews: 39,
      supplier: 'NRCRI Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00105',
      germination: '86%',
      purity: '94%',
      bgColor: 'orange',
      description: 'UMUSPO 3 orange-fleshed sweet potato variety rich in beta-carotene. Promoted for nutrition improvement programs across Nigeria.',
      features: ['Orange fleshed (beta-carotene)', 'Nutrition program variety', 'Matures in 3-4 months', 'Virus resistant'],
      inStock: true
    },

    // ── CASH CROPS ──
    {
      id: 'PRD-029',
      name: 'Sesame Seeds (E8)',
      fullName: 'Sesame Seeds - E8 Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cash Crops',
      region: 'North Central',
      price: 16500,
      unit: 'kg',
      stock: 260,
      rating: 4.5,
      reviews: 61,
      supplier: 'Sahel Agri Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00223',
      germination: '88%',
      purity: '96%',
      bgColor: 'yellow',
      description: 'E8 sesame variety with high oil content and excellent export quality. Nigeria is one of the world\'s largest sesame exporters.',
      features: ['Export grade quality', 'High oil content (52%)', 'Maturity: 85-95 days', 'White seed colour'],
      inStock: true
    },
    {
      id: 'PRD-030',
      name: 'Sesame Seeds (NCRIBEN-04E)',
      fullName: 'Sesame Seeds - NCRIBEN-04E',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cash Crops',
      region: 'North East',
      price: 14000,
      unit: 'kg',
      stock: 180,
      rating: 4.3,
      reviews: 44,
      supplier: 'Sahel Agri Seeds',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00224',
      germination: '86%',
      purity: '95%',
      bgColor: 'yellow',
      description: 'NCRIBEN-04E is an improved sesame variety with resistance to phytophthora blight and good adaptation to the northern states.',
      features: ['Blight resistant', 'High seed yield', 'Matures in 90-100 days', 'Drought tolerant'],
      inStock: true
    },
    {
      id: 'PRD-031',
      name: 'Sunflower Seeds (SAMRO II)',
      fullName: 'Sunflower Seeds - SAMRO II Hybrid',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cash Crops',
      region: 'North West',
      price: 22000,
      unit: 'kg',
      stock: 145,
      rating: 4.2,
      reviews: 29,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'none',
      verificationNumber: null,
      germination: '84%',
      purity: '94%',
      bgColor: 'yellow',
      description: 'SAMRO II sunflower hybrid suitable for dry season cultivation in northern Nigeria under irrigation. Used for oil production.',
      features: ['Good oil yield', 'Dry season suitable', 'Matures in 95-110 days', 'High market value'],
      inStock: true
    },
    {
      id: 'PRD-032',
      name: 'Cocoa Seedlings',
      fullName: 'Cocoa Seedlings - Hybrid Variety',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cash Crops',
      region: 'South West',
      price: 45000,
      unit: 'bundle',
      stock: 60,
      rating: 4.8,
      reviews: 34,
      supplier: 'CRIN Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00378',
      germination: '95%',
      purity: '99%',
      bgColor: 'orange',
      description: 'Hybrid cocoa seedlings from CRIN (Cocoa Research Institute of Nigeria). High yielding and resistant to black pod disease.',
      features: ['Black pod resistant', 'High yielding (2-3kg/tree)', 'CRIN certified', 'Early bearing (3rd year)'],
      inStock: true
    },
    {
      id: 'PRD-033',
      name: 'Cotton Seeds (SAMCOT 9)',
      fullName: 'Cotton Seeds - SAMCOT 9',
      emoji: '🌱',
      inputType: 'seeds',
      subCategory: 'Cash Crops',
      region: 'North West',
      price: 20000,
      unit: 'kg',
      stock: 0,
      rating: 4.0,
      reviews: 22,
      supplier: 'Northern Seeds Ltd',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-2024-00256',
      germination: '85%',
      purity: '95%',
      bgColor: 'green',
      description: 'SAMCOT 9 is an improved cotton variety developed for the Sudan and Guinea savanna zones of Nigeria. Good fibre quality.',
      features: ['Good fibre quality', 'Bollworm tolerant', 'Matures in 160-180 days', 'High lint percentage'],
      inStock: false
    },

    // ── FERTILIZERS & INPUTS ──
    {
      id: 'PRD-034',
      name: 'NPK Fertilizer (15:15:15)',
      fullName: 'NPK Compound Fertilizer 15:15:15',
      emoji: '🌱',
      inputType: 'fertilizers',
      subCategory: 'Fertilizers',
      region: 'All Regions',
      price: 28000,
      unit: '50kg bag',
      stock: 1200,
      rating: 4.6,
      reviews: 189,
      supplier: 'Notore Chemical',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'FMARD-FERT-00123',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'Balanced NPK compound fertilizer suitable for all crops at planting. NASC-certified and subsidized for cooperative members.',
      features: ['Balanced nutrient ratio', 'Suitable for all crops', 'Government subsidy eligible', 'FMARD approved'],
      inStock: true
    },
    {
      id: 'PRD-035',
      name: 'Urea Fertilizer (46%N)',
      fullName: 'Urea Nitrogen Fertilizer 46%',
      emoji: '🌱',
      inputType: 'fertilizers',
      subCategory: 'Fertilizers',
      region: 'All Regions',
      price: 22000,
      unit: '50kg bag',
      stock: 980,
      rating: 4.5,
      reviews: 145,
      supplier: 'Indorama Eleme Fertilizers',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'FMARD-FERT-00124',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'High nitrogen urea fertilizer for top-dressing cereals at 3-4 weeks after planting. Made in Nigeria by Indorama Eleme.',
      features: ['46% nitrogen content', 'For cereal top-dressing', 'Made in Nigeria', 'FMARD approved'],
      inStock: true
    },
    {
      id: 'PRD-036',
      name: 'Single Super Phosphate',
      fullName: 'Single Super Phosphate (SSP) Fertilizer',
      emoji: '🌱',
      inputType: 'fertilizers',
      subCategory: 'Fertilizers',
      region: 'All Regions',
      price: 18500,
      unit: '50kg bag',
      stock: 560,
      rating: 4.3,
      reviews: 87,
      supplier: 'Notore Chemical',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'FMARD-FERT-00125',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'Single super phosphate promotes root development and early crop establishment. Ideal for legumes and vegetables.',
      features: ['Promotes root growth', 'Good for legumes', 'Contains sulphur', 'FMARD approved'],
      inStock: true
    },

    // ── AGROCHEMICALS ──
    {
      id: 'PRD-037',
      name: 'Roundup Herbicide (1L)',
      fullName: 'Roundup Glyphosate Herbicide 1 Litre',
      emoji: '🌱',
      inputType: 'crop-protect',
      subCategory: 'Agrochemicals',
      region: 'All Regions',
      price: 6500,
      unit: '1L bottle',
      stock: 2400,
      rating: 4.7,
      reviews: 234,
      supplier: 'Bayer CropScience Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-AGROCHEM-00567',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'Roundup is a broad-spectrum systemic herbicide for weed control before planting. Approved for use on all major Nigerian crops.',
      features: ['Broad spectrum', 'Pre-planting use', 'NASC approved', 'Cost effective'],
      inStock: true
    },
    {
      id: 'PRD-038',
      name: 'Karate Insecticide (1L)',
      fullName: 'Karate Lambda-cyhalothrin Insecticide',
      emoji: '🌱',
      inputType: 'crop-protect',
      subCategory: 'Agrochemicals',
      region: 'All Regions',
      price: 5800,
      unit: '1L bottle',
      stock: 1800,
      rating: 4.6,
      reviews: 178,
      supplier: 'Syngenta Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-AGROCHEM-00312',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'Karate is a broad-spectrum insecticide effective against a wide range of pests on cereals, vegetables and legumes.',
      features: ['Broad spectrum insect control', 'Fast knockdown', 'Rainfast formula', 'Safe for bees when applied correctly'],
      inStock: true
    },
    {
      id: 'PRD-039',
      name: 'Ridomil Gold Fungicide',
      fullName: 'Ridomil Gold MZ Fungicide (1kg)',
      emoji: '🌱',
      inputType: 'crop-protect',
      subCategory: 'Agrochemicals',
      region: 'All Regions',
      price: 8200,
      unit: '1kg pack',
      stock: 890,
      rating: 4.5,
      reviews: 123,
      supplier: 'Syngenta Nigeria',
      supplierVerified: true,
      verification: 'nasc',
      verificationNumber: 'NASC-AGROCHEM-00289',
      germination: null,
      purity: null,
      bgColor: 'blue',
      description: 'Ridomil Gold MZ is a systemic + contact fungicide effective against downy mildew, Pythium and Phytophthora diseases.',
      features: ['Systemic + contact action', 'Controls downy mildew', 'Pythium control', 'NASC approved'],
      inStock: true
    },
    {
      id: 'PRD-040',
      name: 'Uprooting Herbicide (2.4-D)',
      fullName: '2.4-D Amine Herbicide (1 Litre)',
      emoji: '🌱',
      inputType: 'crop-protect',
      subCategory: 'Herbicides',
      region: 'All Regions',
      price: 4200,
      unit: '1L bottle',
      stock: 1500,
      rating: 4.2,
      reviews: 98,
      supplier: 'Jubaili Agrotec Nigeria',
      supplierVerified: true,
      verification: 'nafdac',
      verificationNumber: 'NAFDAC-PEST-2024-1056',
      germination: null,
      purity: null,
      bgColor: 'purple',
      description: '2.4-D Amine is a selective broadleaf herbicide for weed control in cereals, rice and maize. Very cost-effective for large-scale farmers.',
      features: ['Selective broadleaf control', 'Safe on cereals and rice', 'Cost effective', 'NAFDAC approved'],
      inStock: true
    },

    /* ── ADDITIONAL FERTILIZERS ── */
    {
      id: 'FRT-004',
      inputType: 'fertilizers', subCategory: 'DAP',
      name: 'DAP (Di-Ammonium Phosphate)', fullName: 'DAP 18-46-0 - Starter Fertilizer (50kg)',
      emoji: '🌱', bgColor: 'blue', region: 'All Regions',
      price: 32000, unit: '50kg bag', minOrder: 1, stock: 540,
      rating: 4.5, reviews: 72,
      supplier: 'Indorama Eleme Fertilizers', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-FERT-2024-0034',
      germination: null, purity: null, inStock: true,
      description: 'Di-Ammonium Phosphate - the gold standard starter fertilizer, rich in phosphorus for strong root development. Widely used for rice, maize and wheat.',
      features: ['18% N, 46% P₂O₅', 'Promotes root development', 'Best applied at planting', 'Good for alkaline soils']
    },
    {
      id: 'FRT-005',
      inputType: 'fertilizers', subCategory: 'Organic & Compost',
      name: 'Premium Organic Compost', fullName: 'Premium Organic Compost - 25kg Bag',
      emoji: '🌱', bgColor: 'green', region: 'All Regions',
      price: 5500, unit: '25kg bag', minOrder: 2, stock: 2000,
      rating: 4.3, reviews: 143,
      supplier: 'GreenGrow Organics', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-FERT-2024-0088',
      germination: null, purity: null, inStock: true,
      description: 'Premium organic compost from composted crop residues, poultry manure and vermicompost. Improves soil structure, water retention and microbial activity.',
      features: ['Improves soil structure', 'Long-lasting nutrient release', 'Safe for all crops', 'NAFDAC registered']
    },
    {
      id: 'FRT-006',
      inputType: 'fertilizers', subCategory: 'Foliar Feed',
      name: 'Multi-Nutrient Foliar Fertilizer', fullName: 'Multi-Nutrient Foliar Feed - 1 Litre',
      emoji: '🌱', bgColor: 'blue', region: 'All Regions',
      price: 4500, unit: 'litre', minOrder: 1, stock: 850,
      rating: 4.2, reviews: 56,
      supplier: 'Jubaili Agrotec', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-FERT-2024-0102',
      germination: null, purity: null, inStock: true,
      description: 'Complete foliar fertilizer with N, P, K and trace elements. Fast-acting spray corrects nutrient deficiencies and boosts yield at critical growth stages.',
      features: ['Complete micronutrient package', 'Fast-acting foliar application', 'Suitable for all crops', 'Mixes with pesticides']
    },

    /* ── ADDITIONAL CROP PROTECTION ── */
    {
      id: 'CPR-006',
      inputType: 'crop-protect', subCategory: 'Fungicides',
      name: 'Ridomil Gold MZ (1kg)', fullName: 'Ridomil Gold MZ 68 WG - Systemic Fungicide 1kg',
      emoji: '🌱', bgColor: 'purple', region: 'All Regions',
      price: 8200, unit: '1kg pack', minOrder: 1, stock: 890,
      rating: 4.5, reviews: 123,
      supplier: 'Syngenta Nigeria', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-PEST-2024-1112',
      germination: null, purity: null, inStock: true,
      description: 'Systemic + contact fungicide providing curative and preventive control of Downy Mildew, Late Blight and Phytophthora diseases.',
      features: ['Systemic + contact action', 'Controls Downy Mildew & Late Blight', 'Suitable for tomato, potato, maize', 'Apply preventively for best results']
    },
    {
      id: 'CPR-007',
      inputType: 'crop-protect', subCategory: 'Bio-Pesticides',
      name: 'Neem-Based Bio-Pesticide', fullName: 'Neemix Organic Bio-Pesticide - 1 Litre',
      emoji: '🌱', bgColor: 'green', region: 'All Regions',
      price: 3200, unit: 'litre', minOrder: 1, stock: 340,
      rating: 4.1, reviews: 43,
      supplier: 'GreenGrow Organics', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-PEST-2024-1156',
      germination: null, purity: null, inStock: true,
      description: 'Cold-pressed neem oil that disrupts insect growth cycles. Safe for beneficial insects. Suitable for organic farming certification.',
      features: ['Safe for bees and beneficials', 'Organic farming compatible', 'Controls aphids, whiteflies, mites', 'NAFDAC registered']
    },

    /* ── EQUIPMENT & TOOLS ── */
    {
      id: 'EQP-001',
      inputType: 'equipment', subCategory: 'Sprayers',
      name: 'Knapsack Sprayer (16 Litre)', fullName: 'Manual Knapsack Sprayer 16L - Adjustable Nozzle',
      emoji: '🌱', bgColor: 'blue', region: 'All Regions',
      price: 12500, unit: 'unit', minOrder: 1, stock: 280,
      rating: 4.3, reviews: 156,
      supplier: 'Farmtec Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Durable 16-litre knapsack sprayer with adjustable nozzle for herbicides, pesticides and foliar fertilizers. Ergonomic padded straps.',
      features: ['16-litre tank', 'Adjustable nozzle (mist to jet)', 'Padded shoulder straps', 'Anti-drip valve']
    },
    {
      id: 'EQP-002',
      inputType: 'equipment', subCategory: 'Sprayers',
      name: 'Motorised Power Sprayer (20L)', fullName: 'Motorised Power Sprayer 20L - 2-Stroke Engine',
      emoji: '🌱', bgColor: 'yellow', region: 'All Regions',
      price: 85000, unit: 'unit', minOrder: 1, stock: 45,
      rating: 4.5, reviews: 38,
      supplier: 'Farmtec Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Motorised 2-stroke knapsack sprayer for large-scale application. Covers 4x the area of a manual sprayer per hour. Includes 4 nozzle heads.',
      features: ['2-stroke engine', '20-litre tank', '4 nozzle heads included', 'Covers 1 ha in 2-3 hours']
    },
    {
      id: 'EQP-003',
      inputType: 'equipment', subCategory: 'Irrigation Kits',
      name: 'Drip Irrigation Kit (1 Acre)', fullName: 'Drip Irrigation Starter Kit - 1 Acre Coverage',
      emoji: '🌱', bgColor: 'blue', region: 'All Regions',
      price: 145000, unit: 'kit', minOrder: 1, stock: 28,
      rating: 4.7, reviews: 22,
      supplier: 'Agrico Irrigation Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Complete drip irrigation starter kit for 1 acre. Includes mainline, drip tape, connectors, filter and pressure regulator. Reduces water use by 60%.',
      features: ['Covers 1 acre', '60% water saving vs flood', 'Reduces disease incidence', 'Suitable for vegetables and row crops']
    },
    {
      id: 'EQP-004',
      inputType: 'equipment', subCategory: 'Hand Tools',
      name: 'Premium Hoe & Cutlass Set', fullName: 'Premium Hoe & Cutlass Farming Set - 2 Piece',
      emoji: '⛏️', bgColor: 'brown', region: 'All Regions',
      price: 6500, unit: 'set', minOrder: 1, stock: 800,
      rating: 4.2, reviews: 94,
      supplier: 'Farmtec Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Heavy-duty hoe and cutlass set with hardened steel blades and ergonomic wooden handles. For land clearing, ridging and weeding.',
      features: ['Hardened steel blades', 'Ergonomic wooden handles', 'Rust-resistant coating', 'Suitable for all soil types']
    },
    {
      id: 'EQP-005',
      inputType: 'equipment', subCategory: 'Threshers & Mills',
      name: 'Manual Maize Sheller', fullName: 'Manual Maize Sheller - Cast Iron Drum Type',
      emoji: '⚙️', bgColor: 'yellow', region: 'All Regions',
      price: 18000, unit: 'unit', minOrder: 1, stock: 120,
      rating: 4.4, reviews: 61,
      supplier: 'Farmtec Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Cast iron drum maize sheller that processes 200-300 kg/hour. Reduces post-harvest losses by shelling grain quickly and cleanly.',
      features: ['200-300 kg/hour capacity', 'No electricity needed', 'Low grain breakage', 'Durable cast iron construction']
    },

    /* ── POST-HARVEST & STORAGE ── */
    {
      id: 'PHV-001',
      inputType: 'post-harvest', subCategory: 'Grain Bags',
      name: 'PICS Triple-Layer Storage Bags', fullName: 'PICS Hermetic Storage Bags - 100kg (Pack of 3)',
      emoji: '🌱', bgColor: 'blue', region: 'All Regions',
      price: 4500, unit: 'pack of 3', minOrder: 1, stock: 1500,
      rating: 4.8, reviews: 223,
      supplier: 'GrainSafe Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'PICS hermetic bags create an oxygen-free environment killing storage insects without chemicals. Endorsed by USAID and FAO. Used across West Africa.',
      features: ['Triple-layer hermetic technology', 'No fumigants needed', '100kg capacity per bag', 'Preserves quality 6-12 months']
    },
    {
      id: 'PHV-002',
      inputType: 'post-harvest', subCategory: 'Fumigants',
      name: 'Phostoxin Aluminium Phosphide Tablets', fullName: 'Phostoxin 56% ALP - Grain Fumigant (50 tablets)',
      emoji: '⚗️', bgColor: 'purple', region: 'All Regions',
      price: 3800, unit: 'tin', minOrder: 1, stock: 420,
      rating: 4.5, reviews: 87,
      supplier: 'Jubaili Agrotec', supplierVerified: true,
      verification: 'nafdac', verificationNumber: 'NAFDAC-PEST-2024-2001',
      germination: null, purity: null, inStock: true,
      description: 'Aluminium phosphide fumigant tablets for stored grain protection. NAFDAC registered. ⚠️ Use only with proper protective equipment.',
      features: ['Highly effective grain fumigant', 'Controls all storage insects', 'NAFDAC registered', '⚠️ Use with PPE only']
    },
    {
      id: 'PHV-003',
      inputType: 'post-harvest', subCategory: 'Weighing Scales',
      name: 'Digital Platform Scale (300kg)', fullName: 'Digital Platform Scale 300kg - Solar Rechargeable',
      emoji: '⚖️', bgColor: 'blue', region: 'All Regions',
      price: 35000, unit: 'unit', minOrder: 1, stock: 65,
      rating: 4.3, reviews: 41,
      supplier: 'Farmtec Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Heavy-duty digital platform scale - 300kg capacity, accurate to 100g. Solar-rechargeable battery. Used at farm gates and produce markets.',
      features: ['300kg max capacity', '100g accuracy', 'Solar-rechargeable battery', 'Stainless steel platform']
    },
    {
      id: 'PHV-004',
      inputType: 'post-harvest', subCategory: 'Silos & Drums',
      name: 'Metal Grain Silo (1 Tonne)', fullName: 'Galvanised Metal Grain Silo - 1 Tonne Capacity',
      emoji: '🌱', bgColor: 'yellow', region: 'All Regions',
      price: 185000, unit: 'unit', minOrder: 1, stock: 18,
      rating: 4.6, reviews: 14,
      supplier: 'GrainSafe Nigeria', supplierVerified: true,
      verification: 'supplier', verificationNumber: null,
      germination: null, purity: null, inStock: true,
      description: 'Galvanised steel grain silo - 1 tonne capacity. Rodent-proof, moisture-resistant, designed for the Nigerian climate. Delivered flat-packed with assembly tools.',
      features: ['1-tonne capacity', 'Galvanised steel - rust resistant', 'Rodent and moisture proof', 'Flat-packed for easy transport']
    }
  ],

  /* ── CATEGORIES ── */
  categories: ['All Crops', 'Cereals', 'Legumes', 'Vegetables', 'Tubers', 'Cash Crops', 'Fertilizers', 'Agrochemicals'],

  /* ── REGIONS ── */
  regions: ['All Regions', 'North West', 'North East', 'North Central', 'South West', 'South East', 'South South'],

  /* ── ORDERS ── */
  orders: [
    {
      id: 'AGR-2026-001234',
      date: 'February 18, 2026',
      items: [
        { name: 'Hybrid Maize Seeds', emoji: '🌱', qty: 2, price: 30000 },
        { name: 'Rice Seeds (FARO 44)', emoji: '🌱', qty: 1, price: 25000 },
        { name: 'Tomato Seeds', emoji: '🌱', qty: 5, price: 40000 }
      ],
      subtotal: 95000,
      delivery: 3500,
      service: 500,
      discount: 5000,
      total: 94000,
      status: 'in-transit',
      expected: 'February 21-23, 2026',
      address: 'No. 45 Ahmadu Bello Way, Kaduna, Nigeria',
      paymentMethod: 'Agric Credit',
      trackingCode: 'GIG-2026-5678'
    },
    {
      id: 'AGR-2026-001188',
      date: 'February 10, 2026',
      items: [
        { name: 'Hybrid Maize Seeds', emoji: '🌱', qty: 1, price: 15000 },
        { name: 'Cassava Stems (TME 419)', emoji: '🌱', qty: 2, price: 24000 },
        { name: 'Tomato Seeds', emoji: '🌱', qty: 1, price: 8000 }
      ],
      subtotal: 47000,
      delivery: 0,
      service: 500,
      discount: 2500,
      total: 45000,
      status: 'delivered',
      expected: 'February 12, 2026',
      address: 'No. 45 Ahmadu Bello Way, Kaduna, Nigeria',
      paymentMethod: 'Agric Credit',
      trackingCode: 'KWIK-2024-3456'
    },
    {
      id: 'AGR-2026-001087',
      date: 'January 28, 2026',
      items: [
        { name: 'Rice Seeds (FARO 44)', emoji: '🌱', qty: 1, price: 25000 }
      ],
      subtotal: 25000,
      delivery: 3500,
      service: 500,
      discount: 0,
      total: 29000,
      status: 'cancelled',
      expected: null,
      address: 'No. 45 Ahmadu Bello Way, Kaduna, Nigeria',
      paymentMethod: 'Card',
      trackingCode: null
    },
    {
      id: 'AGR-2026-001050',
      date: 'January 15, 2026',
      items: [
        { name: 'NPK Fertilizer (15:15:15)', emoji: '🌱', qty: 10, price: 280000 },
        { name: 'Urea Fertilizer', emoji: '🌱', qty: 5, price: 110000 }
      ],
      subtotal: 390000,
      delivery: 5000,
      service: 1000,
      discount: 15000,
      total: 381000,
      status: 'delivered',
      expected: 'January 18, 2026',
      address: 'No. 45 Ahmadu Bello Way, Kaduna, Nigeria',
      paymentMethod: 'Agric Credit',
      trackingCode: 'GIG-2026-4123'
    },
    {
      id: 'AGR-2025-000987',
      date: 'December 5, 2025',
      items: [
        { name: 'Cowpea Seeds (IT99K-573)', emoji: '🌱', qty: 3, price: 39000 },
        { name: 'Soybean Seeds', emoji: '🌱', qty: 2, price: 32000 },
        { name: 'Karate Insecticide', emoji: '🌱', qty: 5, price: 29000 }
      ],
      subtotal: 100000,
      delivery: 4000,
      service: 500,
      discount: 0,
      total: 104500,
      status: 'delivered',
      expected: 'December 9, 2025',
      address: 'No. 45 Ahmadu Bello Way, Kaduna, Nigeria',
      paymentMethod: 'Wallet',
      trackingCode: 'KWIK-2025-8901'
    }
  ],

  /* ── EXPERTS ── */
  experts: [
    {
      id: 'EXP-001',
      name: 'Dr. Adewale Ogunlade',
      emoji: '🌱‍🌱',
      title: 'Agricultural Extension Officer',
      institution: 'Federal Ministry of Agriculture, Abuja',
      email: 'adewale.ogunlade@agric.gov.ng',
      rating: 4.9,
      reviews: 234,
      experience: 15,
      sessions: 234,
      responseTime: '< 2 hours',
      fee: 5000,
      verified: true,
      specializations: ['Crop Production', 'Soil Science', 'Irrigation', 'Pest Management'],
      languages: ['English', 'Yoruba'],
      availability: { 'Mon - Fri': '9:00 AM - 5:00 PM', 'Saturday': '10:00 AM - 2:00 PM', 'Sunday': 'Unavailable' },
      bio: 'Dr. Adewale Ogunlade is a seasoned agricultural extension officer with over 15 years of experience. Specializes in crop production, soil management, and sustainable farming across Nigeria.',
      qualifications: ['PhD Agricultural Science - University of Ibadan', 'MSc Crop Production - Ahmadu Bello University', 'Certified Extension Officer - NAERLS']
    },
    {
      id: 'EXP-002',
      name: 'Dr. Chioma Nwosu',
      emoji: '🌱‍🌱',
      title: 'Agronomist',
      institution: 'University of Nigeria, Nsukka',
      email: 'chioma.nwosu@unn.edu.ng',
      rating: 4.8,
      reviews: 189,
      experience: 12,
      sessions: 189,
      responseTime: '< 3 hours',
      fee: 4500,
      verified: true,
      specializations: ['Pest Control', 'Integrated Pest Management', 'Vegetable Farming', 'Post-Harvest'],
      languages: ['English', 'Igbo'],
      availability: { 'Mon - Fri': '8:00 AM - 4:00 PM', 'Saturday': '9:00 AM - 12:00 PM', 'Sunday': 'Unavailable' },
      bio: 'Dr. Chioma Nwosu is an agronomist with deep expertise in integrated pest management and vegetable production systems in southeastern Nigeria.',
      qualifications: ['PhD Agronomy - University of Nigeria, Nsukka', 'MSc Plant Science - University of Ibadan', 'IPM Certified Trainer - FAO']
    },
    {
      id: 'EXP-003',
      name: 'Prof. Ibrahim Mohammed',
      emoji: '🌱‍🌱',
      title: 'Soil Scientist',
      institution: 'Ahmadu Bello University, Zaria',
      email: 'ibrahim.mohammed@abu.edu.ng',
      rating: 4.9,
      reviews: 156,
      experience: 20,
      sessions: 156,
      responseTime: '< 4 hours',
      fee: 6000,
      verified: true,
      specializations: ['Soil Health', 'Fertilization', 'Land Degradation', 'Irrigation Science'],
      languages: ['English', 'Hausa'],
      availability: { 'Mon - Thu': '10:00 AM - 4:00 PM', 'Friday': '10:00 AM - 12:00 PM', 'Sat - Sun': 'Unavailable' },
      bio: 'Professor Ibrahim Mohammed has 20 years of soil science research at ABU Zaria. Expert in soil fertility management and land reclamation in the northern savanna.',
      qualifications: ['PhD Soil Science - Ahmadu Bello University', 'MSc Soil Chemistry - University of Reading, UK', 'Fellow - Soil Science Society of Nigeria']
    },
    {
      id: 'EXP-004',
      name: 'Mrs. Blessing Okoro',
      emoji: '🌱‍🌱',
      title: 'Farm Business Consultant',
      institution: 'Agribusiness Development Nigeria',
      email: 'blessing.okoro@agribizng.com',
      rating: 4.7,
      reviews: 209,
      experience: 8,
      sessions: 209,
      responseTime: '< 1 hour',
      fee: 3500,
      verified: true,
      specializations: ['Agribusiness', 'Farm Marketing', 'Cooperative Management', 'Finance'],
      languages: ['English', 'Igbo', 'Pidgin'],
      availability: { 'Mon - Fri': '7:00 AM - 6:00 PM', 'Saturday': '8:00 AM - 2:00 PM', 'Sunday': 'Unavailable' },
      bio: 'Mrs. Blessing Okoro is a farm business consultant helping Nigerian farmers build profitable agribusinesses. Specializes in cooperative management and agricultural marketing.',
      qualifications: ['MBA Agribusiness - Lagos Business School', 'BSc Agriculture - Michael Okpara University', 'Certified Farm Business Advisor - NIFAA']
    },
    {
      id: 'EXP-005',
      name: 'Mr. Yusuf Abdullahi',
      emoji: '🌱‍🌱',
      title: 'Livestock Specialist',
      institution: 'National Animal Production Research Institute',
      email: 'yusuf.abdullahi@napri.gov.ng',
      rating: 4.8,
      reviews: 178,
      experience: 10,
      sessions: 178,
      responseTime: '< 2 hours',
      fee: 4000,
      verified: true,
      specializations: ['Poultry Farming', 'Animal Health', 'Dairy Cattle', 'Livestock Nutrition'],
      languages: ['English', 'Hausa', 'Fulfulde'],
      availability: { 'Mon - Fri': '8:00 AM - 5:00 PM', 'Saturday': '9:00 AM - 1:00 PM', 'Sunday': 'Unavailable' },
      bio: 'Mr. Yusuf Abdullahi is a livestock production specialist at NAPRI Zaria with expertise in poultry, dairy cattle and small ruminant management.',
      qualifications: ['MSc Animal Science - Usmanu Danfodiyo University', 'BSc Animal Production - ABU Zaria', 'Certified Livestock Consultant - NVMA']
    },
    {
      id: 'EXP-006',
      name: 'Dr. Fatima Bello',
      emoji: '🌱‍⚕️',
      title: 'Plant Pathologist',
      institution: 'Institute for Agricultural Research, Zaria',
      email: 'fatima.bello@iar.edu.ng',
      rating: 4.9,
      reviews: 145,
      experience: 14,
      sessions: 145,
      responseTime: '< 3 hours',
      fee: 5500,
      verified: true,
      specializations: ['Disease Control', 'Diagnostics', 'Fungal Diseases', 'Crop Protection'],
      languages: ['English', 'Hausa'],
      availability: { 'Mon - Fri': '9:00 AM - 4:00 PM', 'Saturday': 'By appointment', 'Sunday': 'Unavailable' },
      bio: 'Dr. Fatima Bello is a plant pathologist at IAR Zaria with expertise in diagnosing and managing crop diseases across Nigeria\'s agricultural zones.',
      qualifications: ['PhD Plant Pathology - Ahmadu Bello University', 'MSc Plant Protection - University of Ibadan', 'Member - Nigerian Phytopathological Society']
    }
  ],

  /* ── COURSES ── */
  courses: [
    {
      id: 'CRS-001',
      title: 'Maize Farming Masterclass',
      emoji: '🌱',
      instructor: 'Dr. Adewale Ogunlade',
      duration: '6 hours',
      modules: 8,
      students: 1245,
      rating: 4.8,
      reviews: 234,
      price: 0,
      isFree: true,
      level: 'Beginner',
      language: 'English',
      bgColor: 'green',
      description: 'Learn everything about hybrid maize cultivation from seed selection to harvest.',
      topics: ['Modern hybrid maize seed selection', 'Land preparation and soil testing', 'Optimal planting techniques', 'Irrigation and water management', 'Fertilizer application schedules', 'Pest and disease control', 'Harvesting and post-harvest handling', 'Marketing and profitability analysis']
    },
    {
      id: 'CRS-002',
      title: 'Rice Cultivation Essentials',
      emoji: '🌱',
      instructor: 'Prof. Ibrahim Mohammed',
      duration: '4 hours',
      modules: 6,
      students: 890,
      rating: 4.5,
      reviews: 156,
      price: 5000,
      isFree: false,
      level: 'Intermediate',
      language: 'English',
      bgColor: 'yellow',
      description: 'Master rice farming techniques for Nigerian climate conditions.',
      topics: ['Rice ecology in Nigeria', 'FARO variety selection', 'Nursery preparation', 'Transplanting techniques', 'Water management', 'Weed and pest control']
    },
    {
      id: 'CRS-003',
      title: 'Tomato Farming Business',
      emoji: '🌱',
      instructor: 'Mrs. Blessing Okoro',
      duration: '5 hours',
      modules: 7,
      students: 2104,
      rating: 4.9,
      reviews: 456,
      price: 0,
      isFree: true,
      level: 'Beginner',
      language: 'English',
      bgColor: 'pink',
      description: 'Turn tomato farming into a profitable business venture.',
      topics: ['Variety selection for profit', 'Greenhouse vs open field', 'Drip irrigation setup', 'Disease management', 'Harvest timing for markets', 'Price negotiation and sales', 'Post-harvest loss prevention']
    },
    {
      id: 'CRS-004',
      title: 'Cassava Production Guide',
      emoji: '🌱',
      instructor: 'Dr. Chioma Nwosu',
      duration: '3 hours',
      modules: 5,
      students: 567,
      rating: 4.5,
      reviews: 98,
      price: 3500,
      isFree: false,
      level: 'Beginner',
      language: 'English',
      bgColor: 'orange',
      description: 'Complete guide to cassava production and processing in Nigeria.',
      topics: ['Improved variety selection', 'Land preparation', 'Planting and weed control', 'Pest management', 'Harvesting and processing']
    },
    {
      id: 'CRS-005',
      title: 'Soil Health Management',
      emoji: '🌱',
      instructor: 'Prof. Ibrahim Mohammed',
      duration: '2 hours',
      modules: 4,
      students: 0,
      rating: 0,
      reviews: 0,
      price: 4000,
      isFree: false,
      level: 'Advanced',
      language: 'English',
      bgColor: 'green',
      description: 'Advanced soil health management for high-yield farming.',
      topics: ['Soil testing and interpretation', 'Soil organic matter', 'Fertilizer recommendations', 'Soil conservation']
    },
    {
      id: 'CRS-006',
      title: 'Modern Irrigation Techniques',
      emoji: '🌱',
      instructor: 'Dr. Adewale Ogunlade',
      duration: '4 hours',
      modules: 6,
      students: 445,
      rating: 4.7,
      reviews: 89,
      price: 0,
      isFree: true,
      level: 'Intermediate',
      language: 'English',
      bgColor: 'blue',
      description: 'Learn how to optimize water usage and increase crop yield by 40%.',
      topics: ['Irrigation methods overview', 'Drip irrigation installation', 'Sprinkler systems', 'Water source management', 'Scheduling irrigation', 'Cost-benefit analysis']
    }
  ],

  /* ── AGRO HUBS ── */
  hubs: [
    { id: 'HUB-001', name: 'Kaduna Central Agro Hub', state: 'Kaduna', lga: 'Kaduna North', address: '23 Ahmadu Bello Way, Kaduna', phone: '+234 803 456 7890', hours: 'Mon-Sat: 8:00 AM - 6:00 PM', distance: '2.5 km', capacity: '500 tons', available: '180 tons', crops: ['Maize', 'Sorghum', 'Soybean'] },
    { id: 'HUB-002', name: 'Lagos Island Agro Hub', state: 'Lagos', lga: 'Lagos Island', address: '45 Marina Road, Lagos Island', phone: '+234 805 123 4567', hours: 'Mon-Sat: 7:00 AM - 7:00 PM', distance: '5.2 km', capacity: '300 tons', available: '95 tons', crops: ['Tomato', 'Pepper', 'Vegetables'] },
    { id: 'HUB-003', name: 'Kano Dawanau Agro Hub', state: 'Kano', lga: 'Tarauni', address: 'Dawanau Market Road, Kano', phone: '+234 812 345 6789', hours: 'Mon-Fri: 8:00 AM - 5:00 PM', distance: '12.0 km', capacity: '1000 tons', available: '420 tons', crops: ['Onion', 'Groundnut', 'Sesame'] },
    { id: 'HUB-004', name: 'Ibadan Agro Processing Hub', state: 'Oyo', lga: 'Oluyole', address: 'Challenge Road, Ibadan', phone: '+234 809 876 5432', hours: 'Mon-Sat: 7:30 AM - 6:00 PM', distance: '8.3 km', capacity: '400 tons', available: '210 tons', crops: ['Cassava', 'Cocoa', 'Yam'] },
    { id: 'HUB-005', name: 'Abuja Agro Hub (Gwagwalada)', state: 'FCT', lga: 'Gwagwalada', address: 'Phase 2, Gwagwalada, Abuja', phone: '+234 806 234 5678', hours: 'Mon-Sat: 8:00 AM - 5:30 PM', distance: '34.0 km', capacity: '250 tons', available: '120 tons', crops: ['Maize', 'Rice', 'Vegetables'] },
    { id: 'HUB-006', name: 'Enugu South East Hub', state: 'Enugu', lga: 'Enugu East', address: 'Garriki Road, Enugu', phone: '+234 803 567 8901', hours: 'Mon-Fri: 8:00 AM - 5:00 PM', distance: '6.7 km', capacity: '200 tons', available: '88 tons', crops: ['Cassava', 'Yam', 'Rice'] }
  ],

  /* ── COOPERATIVE MEMBERS (flat list - legacy) ── */
  coopMembers: [
    { id: 'MBR-001', name: 'Musa Aliyu',     phone: '+234 803 456 7891', lga: 'Kaduna North', farmSize: '2.5 ha', crop: 'Maize',   ninVerified: true,  creditScore: 78, loanStatus: 'Active', joinDate: 'Jan 2025' },
    { id: 'MBR-002', name: 'Aisha Mohammed', phone: '+234 805 678 9012', lga: 'Kaduna South', farmSize: '1.8 ha', crop: 'Sorghum', ninVerified: true,  creditScore: 85, loanStatus: 'Repaid', joinDate: 'Feb 2025' },
    { id: 'MBR-003', name: 'Bello Garba',    phone: '+234 812 890 1234', lga: 'Kaduna North', farmSize: '3.2 ha', crop: 'Maize',   ninVerified: true,  creditScore: 72, loanStatus: 'Active', joinDate: 'Jan 2025' },
    { id: 'MBR-004', name: 'Fatima Usman',   phone: '+234 809 012 3456', lga: 'Igabi',        farmSize: '1.2 ha', crop: 'Cowpea', ninVerified: false, creditScore: 60, loanStatus: 'None',   joinDate: 'Mar 2025' },
    { id: 'MBR-005', name: 'Ibrahim Sule',   phone: '+234 806 234 5678', lga: 'Kaduna North', farmSize: '4.0 ha', crop: 'Soybean', ninVerified: true,  creditScore: 90, loanStatus: 'Repaid', joinDate: 'Dec 2024' },
    { id: 'MBR-006', name: 'Hauwa Danjuma',  phone: '+234 803 456 7890', lga: 'Kaura',        farmSize: '2.0 ha', crop: 'Maize',   ninVerified: true,  creditScore: 80, loanStatus: 'Active', joinDate: 'Feb 2025' }
  ],

  /* ── COOPERATIVE (rich object for coop screens) ── */
  cooperative: {
    name: 'Kaduna North Farmers Cooperative',
    regNumber: 'FCA/KD/2018/00234',
    state: 'Kaduna', lga: 'Kaduna North', primaryCrop: 'Maize',
    totalMembers: 120, activeMembers: 113,
    groupWalletBalance: 845000, agricCreditLocked: 620000, freeBalance: 225000,
    activeLoanId: 'LOAN-2026-001', activeLoanAmount: 2500000,
    activeLoanRepaid: 1500000, activeLoanBalance: 1000000,
    lendingInstitution: 'Bank of Agriculture', nextRepaymentDate: 'Mar 15, 2026',
    members: [
      { id: 'MBR-001', name: 'Aminu Ibrahim', phone: '+234 803 111 2222', lga: 'Kaduna North', joined: 'Jan 2024', status: 'active',   paidDues: true,  farmSize: '3.5 ha', crop: 'Maize, Sorghum'  },
      { id: 'MBR-002', name: 'Hauwa Musa',    phone: '+234 805 333 4444', lga: 'Zaria',        joined: 'Jan 2024', status: 'active',   paidDues: true,  farmSize: '2.0 ha', crop: 'Rice, Cowpea'    },
      { id: 'MBR-003', name: 'Usman Garba',   phone: '+234 807 555 6666', lga: 'Sabon Gari',   joined: 'Mar 2024', status: 'active',   paidDues: false, farmSize: '1.5 ha', crop: 'Maize'           },
      { id: 'MBR-004', name: 'Fatima Sule',   phone: '+234 809 777 8888', lga: 'Kaduna South', joined: 'Feb 2024', status: 'active',   paidDues: true,  farmSize: '4.0 ha', crop: 'Tomato, Pepper'  },
      { id: 'MBR-005', name: 'Bala Mohammed', phone: '+234 811 999 0000', lga: "Jema'a",       joined: 'Apr 2024', status: 'inactive', paidDues: false, farmSize: '1.0 ha', crop: 'Groundnut'       },
      { id: 'MBR-006', name: 'Aisha Yakubu',  phone: '+234 813 111 3333', lga: 'Kachia',       joined: 'Jan 2024', status: 'active',   paidDues: true,  farmSize: '2.8 ha', crop: 'Soybean, Maize'  },
    ],
    loanHistory: [
      { id: 'LOAN-2026-001', amount: 2500000, status: 'active',    disbursed: 'Jan 15, 2026', balance: 1000000, repaidPct: 60  },
      { id: 'LOAN-2025-008', amount: 1800000, status: 'completed', disbursed: 'Jun 10, 2025', balance: 0,       repaidPct: 100 },
      { id: 'LOAN-2024-003', amount: 1200000, status: 'completed', disbursed: 'Feb 3, 2024',  balance: 0,       repaidPct: 100 },
    ],
    recentPurchases: [
      { id: 'TXN-C001', date: 'Jan 18, 2026', item: 'Hybrid Maize Seeds - 80kg',  amount: 1200000, category: 'seeds',        supplier: 'SEEDCO Nigeria'             },
      { id: 'TXN-C002', date: 'Jan 22, 2026', item: 'NPK 15-15-15 - 20 bags',     amount: 560000,  category: 'fertilizers',  supplier: 'Notore Chemical Industries'  },
      { id: 'TXN-C003', date: 'Jan 24, 2026', item: 'Cypermethrin 10 EC - 10L',   amount: 60000,   category: 'crop-protect', supplier: 'Jubaili Agrotec'             },
      { id: 'TXN-C004', date: 'Feb 1, 2026',  item: 'Member Dues - 120',          amount: 240000,  category: 'income',       supplier: null                          },
      { id: 'TXN-C005', date: 'Feb 5, 2026',  item: 'Tractor Rental - 3 days',    amount: 45000,   category: 'equipment',    supplier: 'Farmtec Nigeria'             },
    ],
    spendBreakdown: [
      { category: 'Seeds & Planting', pct: 58, color: '#1E8B4C' },
      { category: 'Fertilizers',      pct: 23, color: '#2563EB' },
      { category: 'Crop Protection',  pct: 12, color: '#7C3AED' },
      { category: 'Equipment',        pct: 5,  color: '#D97706' },
      { category: 'Other',            pct: 2,  color: '#9CA3AF' },
    ]
  },

  /* ── WALLET DATA ── */
  wallet: {
    personalBalance: 45750,
    agricCredit: 150000,
    agricCreditSource: 'Bank of Agriculture',
    agricCreditExpiry: 'November 30, 2026',
    totalIncome: 1450000,
    totalSpent: 1204250,
    thisMonth: 185500,
    pending: 2000,
    transactions: [
      { id: 'TXN-001', type: 'credit', title: 'Payment Received', sub: 'From SEEDCO Nigeria', date: 'Feb 18, 2026 - 2:45 PM', amount: 30000 },
      { id: 'TXN-002', type: 'debit',  title: 'Seed Purchase', sub: 'Order #AGR-2026-001234', date: 'Feb 18, 2026 - 10:30 AM', amount: 94000 },
      { id: 'TXN-003', type: 'credit', title: 'Agric Credit Disbursed', sub: 'Bank of Agriculture', date: 'Feb 15, 2026 - 4:20 PM', amount: 150000 },
      { id: 'TXN-004', type: 'debit',  title: 'Expert Consultation', sub: 'Dr. Adewale Ogunlade', date: 'Feb 12, 2026 - 9:15 AM', amount: 5000 },
      { id: 'TXN-005', type: 'credit', title: 'Wallet Funded', sub: 'Bank Transfer', date: 'Feb 10, 2026 - 11:00 AM', amount: 100000 },
      { id: 'TXN-006', type: 'credit', title: 'Product Sold', sub: 'Cassava Stems Order', date: 'Feb 10, 2026 - 11:40 AM', amount: 12000 },
      { id: 'TXN-007', type: 'debit',  title: 'Fertilizer Purchase', sub: 'Order #AGR-2026-001050', date: 'Jan 15, 2026 - 3:10 PM', amount: 381000 },
      { id: 'TXN-008', type: 'credit', title: 'Payment Received', sub: 'Cooperative Loan Repay', date: 'Jan 10, 2026 - 8:00 AM', amount: 50000 }
    ]
  },

  /* ── INSTITUTIONAL DASHBOARD DATA ── */
  institutional: {
    totalDisbursed: 2400000000,
    activeCoops: 1248,
    activeFarmers: 87450,
    repaymentRate: 94.2,
    spendCompliance: 99.1,
    activeStates: 18,
    avgLoanSize: 180000,
    loansDisbursedThisMonth: 342,
    statesData: [
      { state: 'Kano',    farmers: 12400, coops: 187, disbursed: 340000000, repayment: 96, compliance: 99 },
      { state: 'Kaduna',  farmers: 9800,  coops: 142, disbursed: 280000000, repayment: 93, compliance: 99 },
      { state: 'Katsina', farmers: 8200,  coops: 121, disbursed: 240000000, repayment: 95, compliance: 100 },
      { state: 'Kebbi',   farmers: 7100,  coops: 98,  disbursed: 190000000, repayment: 91, compliance: 98 },
      { state: 'Sokoto',  farmers: 6900,  coops: 95,  disbursed: 185000000, repayment: 90, compliance: 99 },
      { state: 'Jigawa',  farmers: 6500,  coops: 88,  disbursed: 172000000, repayment: 94, compliance: 100 },
      { state: 'Borno',   farmers: 5800,  coops: 76,  disbursed: 155000000, repayment: 89, compliance: 98 },
      { state: 'Niger',   farmers: 5200,  coops: 71,  disbursed: 140000000, repayment: 92, compliance: 99 },
      { state: 'Benue',   farmers: 4900,  coops: 65,  disbursed: 128000000, repayment: 95, compliance: 100 },
      { state: 'Plateau', farmers: 4100,  coops: 54,  disbursed: 105000000, repayment: 96, compliance: 100 }
    ],
    spendBreakdown: [
      { category: 'Seeds & Planting Material', percent: 42, color: '#1E8B4C' },
      { category: 'Fertilizers', percent: 31, color: '#22A350' },
      { category: 'Agrochemicals', percent: 16, color: '#5b3fe0' },
      { category: 'Equipment & Tools', percent: 8, color: '#D97706' },
      { category: 'Others', percent: 3, color: '#9CA3AF' }
    ],
    loanQueue: [
      { id: 'LQ-001', coop: 'Kaduna North Farmers Coop', amount: 18500000, members: 124, crop: 'Maize', submitted: 'Feb 16, 2026', status: 'pending', creditScore: 82 },
      { id: 'LQ-002', coop: 'Kano Vegetable Growers', amount: 12000000, members: 89, crop: 'Onion', submitted: 'Feb 15, 2026', status: 'pending', creditScore: 88 },
      { id: 'LQ-003', coop: 'Kebbi Rice Farmers Union', amount: 24000000, members: 156, crop: 'Rice', submitted: 'Feb 14, 2026', status: 'reviewing', creditScore: 91 },
      { id: 'LQ-004', coop: 'Benue Yam Producers Coop', amount: 9500000, members: 67, crop: 'Yam', submitted: 'Feb 13, 2026', status: 'approved', creditScore: 86 },
      { id: 'LQ-005', coop: 'Niger State Soybean Coop', amount: 15000000, members: 98, crop: 'Soybean', submitted: 'Feb 12, 2026', status: 'disbursed', creditScore: 79 }
    ]
  },

  /* ── SELLERS (My Listings mock data) ── */
  supplierListings: [
    { id: 'PRD-001', name: 'Hybrid Maize Seeds', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Cereals', price: 15000, stock: 450, status: 'active', nascVerified: true },
    { id: 'PRD-002', name: 'Rice Seeds (FARO 44)', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Cereals', price: 25000, stock: 280, status: 'active', nascVerified: true },
    { id: 'PRD-015', name: 'Tomato Seeds (Roma VF)', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Vegetables', price: 8000, stock: 850, status: 'active', nascVerified: false },
    { id: 'PRD-024', name: 'Cassava Stems (TME 419)', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Tubers', price: 12000, stock: 125, status: 'active', nascVerified: true },
    { id: 'PRD-005', name: 'Sorghum Seeds (SK 5912)', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Cereals', price: 18000, stock: 0, status: 'out-of-stock', nascVerified: true },
    { id: 'PRD-020', name: 'Spinach Seeds', emoji: '🌱', inputType: 'seeds',
      subCategory: 'Vegetables', price: 6500, stock: 320, status: 'active', nascVerified: false },
    { id: 'NEW-001', name: 'Cowpea Seeds (New Batch)', emoji: '🌱', category: 'Legumes', price: 13500, stock: 0, status: 'draft', nascVerified: false }
  ],

  /* ── SELLER ORDERS RECEIVED ── */
  supplierOrders: [
    { id: 'AGR-2026-001245', customer: 'Adewale Ogunlade', phone: '+234 803 456 7890', items: [{ emoji: '🌱', name: 'Hybrid Maize' }, { emoji: '🌱', name: 'Rice FARO 44' }], more: 1, total: 55000, status: 'pending', date: 'Feb 18, 2026 - 2:45 PM' },
    { id: 'AGR-2026-001238', customer: 'Chioma Nwosu', phone: '+234 805 123 4567', items: [{ emoji: '🌱', name: 'Rice FARO 44' }, { emoji: '🌱', name: 'Tomato Seeds' }], more: 1, total: 33000, status: 'processing', date: 'Feb 18, 2026 - 10:15 AM' },
    { id: 'AGR-2026-001230', customer: 'Ibrahim Mohammed', phone: '+234 807 987 6543', items: [{ emoji: '🌱', name: 'Cassava Stems' }], more: 2, total: 48000, status: 'shipped', date: 'Feb 17, 2026 - 4:30 PM' },
    { id: 'AGR-2026-001220', customer: 'Blessing Okoro', phone: '+234 809 234 5678', items: [{ emoji: '🌱', name: 'Hybrid Maize' }, { emoji: '🌱', name: 'Rice FARO 44' }], more: 1, total: 55000, status: 'delivered', date: 'Feb 16, 2026 - 1:00 PM' }
  ],

  /* ── NOTIFICATIONS ── */
  notifications: [
    { id: 'NOT-001', type: 'order', icon: '🌱', title: 'Order Dispatched', body: 'Your order #AGR-2026-001234 has been picked up by GIG Logistics', time: '2 mins ago', read: false },
    { id: 'NOT-002', type: 'wallet', icon: '🌱', title: 'Agric Credit Received', body: '₦150,000 agricultural credit has been disbursed to your wallet by BOA', time: '3 days ago', read: false },
    { id: 'NOT-003', type: 'loan', icon: '🌱', title: 'Loan Application Update', body: 'Your cooperative loan application is under review', time: '5 days ago', read: true },
    { id: 'NOT-004', type: 'course', icon: '🌱', title: 'New Course Available', body: 'Dr. Adewale has published a new module on Soil Health', time: '1 week ago', read: true },
    { id: 'NOT-005', type: 'order', icon: '✅', title: 'Order Delivered', body: 'Your order #AGR-2026-001188 has been delivered successfully', time: '2 weeks ago', read: true }
  ],

  /* ── WHATSAPP MESSAGES ── */
  waMessages: [
    { from: 'user', text: 'Hi' },
    { from: 'bot', text: '🌱 Welcome to AgroConnect!\n\nI can help you with:\n1️⃣ Check wallet balance\n2️⃣ Browse seeds & inputs\n3️⃣ Track your order\n4️⃣ Get farming tips\n5️⃣ Talk to an expert\n\nReply with a number or type your question 🌱' },
    { from: 'user', text: '1' },
    { from: 'bot', text: '🌱 Your AgroConnect Wallet\n\n🌱 Agric Credit: ₦150,000\n(Spend-locked - marketplace only)\n\n🌱 Personal Balance: ₦45,750\n\nLast updated: just now\n\nReply *menu* to go back' },
    { from: 'user', text: '2' },
    { from: 'bot', text: '🌱 *Available Seeds Near You*\n\n1. Hybrid Maize Seeds - ₦15,000/kg ✅ NASC\n2. Rice FARO 44 - ₦25,000/kg ✅ NASC\n3. Cowpea IT99K - ₦13,000/kg ✅ NASC\n4. Tomato Roma VF - ₦8,000/kg\n5. Soybean TGX - ₦16,000/kg ✅ NASC\n\nReply with a number to order, or visit the app for full catalogue 🌱' }
  ]

};


/* ══════════════════════════════════════════
   BACKWARD COMPATIBILITY
   AC_DATA.seeds returns all seed products
══════════════════════════════════════════ */
Object.defineProperty(AC_DATA, 'seeds', {
  get() { return this.products.filter(p => p.inputType === 'seeds'); },
  enumerable: false
});

export default AC_DATA;
